# yet another markup language   yml -> yaml   \u66F4\u50CFjson\u6587\u4EF6

## \u914D\u7F6E\u670D\u52A1\u7684\u7AEF\u53E3\u53F7
#server:
#  # \u9ED8\u8BA48080
#  port: 8080

spring:
  application:
    # \u5F53\u524D\u5E94\u7528\u7684\u540D\u79F0
    name: springboot01
  # \u914D\u7F6Espringboot\u7684\u73AF\u5883
  profiles:
    # \u8BBE\u7F6E\u5F53\u524D\u73AF\u5883\u4E3Adev(\u5F00\u53D1\u73AF\u5883)
    active: dev

##\u81EA\u884C\u914D\u7F6E\u6D4B\u8BD5\u73AF\u5883 test(port:8082)
#spring:
#  application:
#    name: springboot01
#  profiles:
#    active: test

##\u81EA\u884C\u914D\u7F6E\u6D4B\u8BD5\u73AF\u5883 test(port:8082)
#spring:
#  application:
#    name: springboot01
#  profiles:
#    active: prod

