server:
  port: 8081

spring:
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/boot?serverTimezone=Hongkong&allowMultiQueries=true&characterEncoding=utf8&useUnicode=true&&characterSetResults=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #邮件
  mail:
    host: smtp.163.com
    username: xxx@163.com
    #授权码
    password: xxx
    properties:
      mail:
        debug: true

mybatis:
  #此classpath:后不能有空格，它是字符串；扫描 *Mapper.xml文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启数据库下划线规范到Java驼峰规范的转化
    map-underscore-to-camel-case: true

#输出sql语句日志
logging:
  level:
    com:
      zpark:
        springboot02:
          mapper: debug