server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot?serverTimezone=Hongkong&allowMultiQueries=true&characterEncoding=utf8&useUnicode=true&&characterSetResults=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  security:
#    user:
#      name: sam
#      password: 123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true